events {}

http {
    upstream app_servers {
        server app:3000;    # Docker가 라운드로빈으로 분산
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}